// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAft25JHZKUjl7BQlGWWrGRG82etjS7uH0',
    appId: '1:877876301171:web:b0d4b2b3d204084ca08906',
    messagingSenderId: '877876301171',
    projectId: 'attendance-management-sy-97913',
    authDomain: 'attendance-management-sy-97913.firebaseapp.com',
    storageBucket: 'attendance-management-sy-97913.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4tGXjg2xw-rtPZvX2VhBNHOyCkK1W8Cc',
    appId: '1:877876301171:android:e9092e0c20d56413a08906',
    messagingSenderId: '877876301171',
    projectId: 'attendance-management-sy-97913',
    storageBucket: 'attendance-management-sy-97913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC1iKGUXXGCdO7Cv-ScSqZo2N2HzkAdfo',
    appId: '1:877876301171:ios:0a0f244a256e42a4a08906',
    messagingSenderId: '877876301171',
    projectId: 'attendance-management-sy-97913',
    storageBucket: 'attendance-management-sy-97913.appspot.com',
    iosBundleId: 'com.example.attendanceMangementSystem',
  );
}
